
package clientews.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonaServiceWS", targetNamespace = "http://service.sga.gm.com.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonaServiceWS {


    /**
     * 
     * @return
     *     returns java.util.List<clientews.servicio.Persona>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonas", targetNamespace = "http://service.sga.gm.com.mx/", className = "clientews.servicio.GetPersonas")
    @ResponseWrapper(localName = "getPersonasResponse", targetNamespace = "http://service.sga.gm.com.mx/", className = "clientews.servicio.GetPersonasResponse")
    @Action(input = "http://service.sga.gm.com.mx/PersonaServiceWS/getPersonasRequest", output = "http://service.sga.gm.com.mx/PersonaServiceWS/getPersonasResponse")
    public List<Persona> getPersonas();

}
